root: true
parser: '@typescript-eslint/parser'

extends:
- airbnb
- plugin:@typescript-eslint/recommended

plugins:
- '@typescript-eslint'

rules:
  indent: [ error, tab ]
  no-tabs: off
  no-underscore-dangle: off
  import/extensions: [ error, never ]
  max-len: [ warn, 100 ]
  no-shadow: off
  '@typescript-eslint/no-shadow': error
  object-curly-newline:
  - error
  - ImportDeclaration: never
    ExportDeclaration: always

settings:
  import/resolver:
    node:
      extensions: [ .js, .ts ]
