root: true
parser: '@typescript-eslint/parser'

extends:
- airbnb
- plugin:@typescript-eslint/recommended

plugins:
- '@typescript-eslint'

rules:
  indent: [ error, tab ]
  no-tabs: off
  no-underscore-dangle: off
  import/extensions: [ error, never ]

settings:
  import/resolver:
    node:
      extensions: [ .js, .ts ]
