image: node:20-alpine

build:
  stage: build
  script:
  - npm install
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
  - npm test

pages:
  only: [ main ]
  stage: deploy
  image:
    name: klakegg/hugo:alpine
    entrypoint: [ '' ]
  script:
  - hugo -s website
  artifacts:
    paths:
    - public
