build:
  stage: build
  image: node:20-alpine
  script:
  - npm install
  artifacts:
    paths:
      - node_modules

pages:
  stage: deploy
  image:
    name: klakegg/hugo:alpine
    entrypoint: [ '' ]
  script:
  - hugo -s website
  artifacts:
    paths:
    - public
